# Тактика
- Из импортируемой из-вне функции getMessage() делаем заглушку самой себя(!).

## Заменяемая функция
//services/axios.js
import axios from 'axios'

export function getMessage() {
  return axios.get('http://localhost:3000/message').then(response => {
    return response.data
  })
}


## Место использования функции
//компонент
  async created() {
    try {
      this.message = await getMessage()
    } catch (err) {
      this.error = 'Oops! Something went wrong.'
    }
  }



## Тест

import { getMessage } from '@/services/axios'
jest.mock('@/services/axios')     //из getMessage сделали заглушку самой себя

beforeEach(() => {
  jest.clearAllMocks()
})

describe('MessageDisplay', () => {
  it('Calls getMessage and displays message', async () => {
    const mockMessage = 'Hello from the db'

    getMessage.mockResolvedValueOnce({ text: 'Привет' })
    getMessage.mockRejectedValueOnce('Облом')  // или запускаем Rejected вариант промиса

    const wrapper = mount(MessageDisplay)

    await flushPromises()
    expect(getMessage).toHaveBeenCalledTimes(1)

    const message = wrapper.find('[data-testid="message"]').element.textContent
    expect(message).toEqual(mockMessage)
  })
})













